import { Montserrat } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/components/providers/TanstackProvider";
import BaseNavbar from "./components/BaseNavbar/BaseNavbar";
import AuthProvider from "@/context-providers/AuthProvider";
import { Toaster } from "react-hot-toast";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Bookling",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <AuthProvider>
          <TanstackProvider>
            <main className="bg-gray-50">
              <BaseNavbar />
              <Toaster position="bottom-right" />
              <div className="max-w-7xl mx-auto px-6 py-10 lg:py-20 min-h-screen">
                {children}
              </div>
            </main>
          </TanstackProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
