import { Montserrat } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/components/providers/TanstackProvider";
import BaseNavbar from "./components/BaseNavbar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Bookling",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <TanstackProvider>
          <main className="bg-gray-50">
            <BaseNavbar />
            <div className="max-w-7xl mx-auto px-6 py-28 min-h-screen">
              {children}
            </div>
          </main>
        </TanstackProvider>
      </body>
    </html>
  );
}
